exclude:
  - 'node_modules'
layouts_dir: 'node_modules/uptick-demo-site/dist'
package_name: Bootstrap Mireco
package_github_url: https://github.com/bor3ham/bootstrap-mireco
package_npm_url: https://www.npmjs.com/package/bootstrap-mireco
